# Generated by Django 5.2.17 on 2026-09-23 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0002_alter_recipe_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pantry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="güncellenme tarihi"
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pantries",
                        to="recipes.ingredient",
                        verbose_name="malzemeler",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pantry",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dolap",
                "verbose_name_plural": "Dolaplar",
            },
        ),
        migrations.CreateModel(
            name="ShoppingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100, verbose_name="metin")),
                (
                    "is_checked",
                    models.BooleanField(default=False, verbose_name="işaretli"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="eklenme tarihi"
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_items",
                        to="recipes.ingredient",
                        verbose_name="malzeme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alışveriş Öğesi",
                "verbose_name_plural": "Alışveriş Öğeleri",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="eklenme tarihi"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="recipes.recipe",
                        verbose_name="tarif",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favori",
                "verbose_name_plural": "Favoriler",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "recipe"), name="unique_user_recipe_favorite"
                    )
                ],
            },
        ),
    ]
