# Generated by Django 5.2.17 on 2026-09-24 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("recipes", "0002_alter_recipe_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shoppingitem",
            constraint=models.UniqueConstraint(
                fields=("user", "text"), name="unique_user_shopping_text"
            ),
        ),
    ]
