# Generated by Django 5.2.17 on 2026-09-23 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("gluten", "Gluten"),
                            ("sut", "Süt"),
                            ("yumurta", "Yumurta"),
                            ("kuruyemis", "Kuruyemiş"),
                            ("yer_fistigi", "Yer Fıstığı"),
                            ("balik", "Balık"),
                            ("kabuklu_deniz", "Kabuklu Deniz Ürünleri"),
                            ("soya", "Soya"),
                            ("susam", "Susam"),
                            ("kereviz", "Kereviz"),
                            ("hardal", "Hardal"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="kod",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="ad")),
                (
                    "emoji",
                    models.CharField(blank=True, max_length=8, verbose_name="emoji"),
                ),
            ],
            options={
                "verbose_name": "Alerjen",
                "verbose_name_plural": "Alerjenler",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="ad"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=60, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "emoji",
                    models.CharField(blank=True, max_length=8, verbose_name="emoji"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="sıra"),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="IngredientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="ad"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="sıra"),
                ),
            ],
            options={
                "verbose_name": "Malzeme Grubu",
                "verbose_name_plural": "Malzeme Grupları",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="ad"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "synonyms",
                    models.CharField(
                        blank=True,
                        help_text="Virgülle ayırarak yazın, örn: domatesler, çeri domates",
                        max_length=255,
                        verbose_name="eş anlamlılar",
                    ),
                ),
                (
                    "is_staple",
                    models.BooleanField(
                        default=False,
                        help_text="Her evde bulunduğu varsayılan malzeme (tuz, su, sıvı yağ, karabiber gibi)",
                        verbose_name="temel malzeme",
                    ),
                ),
                (
                    "allergens",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ingredients",
                        to="recipes.allergen",
                        verbose_name="alerjenler",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingredients",
                        to="recipes.ingredientgroup",
                        verbose_name="grup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Malzeme",
                "verbose_name_plural": "Malzemeler",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="başlık")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=170, unique=True, verbose_name="slug"
                    ),
                ),
                ("summary", models.CharField(max_length=200, verbose_name="özet")),
                (
                    "prep_minutes",
                    models.PositiveSmallIntegerField(
                        verbose_name="hazırlık süresi (dk)"
                    ),
                ),
                (
                    "cook_minutes",
                    models.PositiveSmallIntegerField(
                        verbose_name="pişirme süresi (dk)"
                    ),
                ),
                (
                    "servings",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="porsiyon"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("kolay", "Kolay"), ("orta", "Orta")],
                        default="kolay",
                        max_length=10,
                        verbose_name="zorluk",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(blank=True, max_length=8, verbose_name="emoji"),
                ),
                (
                    "steps",
                    models.TextField(
                        help_text="Her satıra bir adım yazın", verbose_name="adımlar"
                    ),
                ),
                ("tips", models.TextField(blank=True, verbose_name="ipuçları")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="yayında"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="oluşturulma tarihi"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipes",
                        to="recipes.category",
                        verbose_name="kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif",
                "verbose_name_plural": "Tarifler",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(max_length=50, verbose_name="miktar")),
                (
                    "is_optional",
                    models.BooleanField(default=False, verbose_name="opsiyonel"),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_ingredients",
                        to="recipes.ingredient",
                        verbose_name="malzeme",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="recipes.recipe",
                        verbose_name="tarif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif Malzemesi",
                "verbose_name_plural": "Tarif Malzemeleri",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipes.RecipeIngredient",
                to="recipes.ingredient",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="unique_recipe_ingredient"
            ),
        ),
    ]
