# Generated by Django 5.2.17 on 2026-09-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=150, unique=True, verbose_name="başlık"),
        ),
    ]
